(()=>{'use strict';
const $=id=>document.getElementById(id),base=String(window.RIVER_ONLINE_ENDPOINT||'').replace(/\/$/,''),name=r=>window.RoomNames.title(r.code),fmt=n=>window.RiverMoney.compact(n),exact=n=>window.RiverMoney.exact(n);
const labels={playing:'正在打牌',waiting:'等待开局',offline:'无人在线',closed:'已关闭',expired:'已过期'};
let token='',rooms=[],timer=null,loading=false,action=null,detailCode='';
try{token=sessionStorage.getItem('river-admin-session')||''}catch{}
const time=n=>n?new Date(n).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Shanghai'}):'—';
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function forget(){token='';try{sessionStorage.removeItem('river-admin-session')}catch{}clearTimeout(timer);rooms=[];$('roomList').replaceChildren();$('dashboard').hidden=true;$('loginPanel').hidden=false;$('logout').hidden=true;for(const id of ['roomDetail','roomConfirm'])if($(id).open)$(id).close()}
async function request(path,data,auth=true){if(!base)throw Error('好友房服务尚未配置。');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const res=await fetch(base+'/api/admin'+path,{method:data===undefined?'GET':'POST',headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(auth?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data),signal:controller.signal,cache:'no-store'});let out;try{out=await res.json()}catch{throw Error('管理服务暂不可用，请稍后重试。')}if(res.status===401&&auth){forget();$('loginNotice').textContent='验证已过期，请重新输入管理口令。'}if(!res.ok)throw Error(out.error||'操作未完成，请重试。');return out}catch(e){if(e.name==='AbortError')throw Error('请求超时，请检查网络后刷新。');throw e}finally{clearTimeout(timeout)}}
function filter(){const query=$('roomSearch').value.trim().toLowerCase(),f=$('roomFilter').value;return rooms.filter(r=>(f==='all'||f==='open'&&!['closed','expired'].includes(r.status)||f==='online'&&r.online>0||f===r.status)&&(name(r)+' '+r.code+' '+r.players.map(p=>p.name).join(' ')).toLowerCase().includes(query))}
function button(label,fn,cls){const b=el('button',cls,label);b.type='button';b.onclick=fn;return b}
function render(){const open=rooms.filter(r=>!['closed','expired'].includes(r.status));$('openCount').textContent=open.length;$('playingCount').textContent=rooms.filter(r=>r.status==='playing').length;$('onlineCount').textContent=rooms.reduce((s,r)=>s+r.online,0);const list=filter();$('listCount').textContent=list.length+' 个房间';const nodes=list.map(r=>{const card=el('article','room-card'),top=el('div','room-card-top'),heading=el('div');heading.append(el('h2','',name(r)),el('p','room-code',r.code));top.append(heading,el('span','status '+r.status,labels[r.status]||'未知状态'));const facts=el('div','room-facts');for(const text of [r.online+' 真人在线',r.bots+' AI',r.occupied+'/'+r.capacity+' 席位',r.blind/2+'/'+r.blind+' 盲注'])facts.append(el('span','',text));const buttons=el('div','room-actions');buttons.append(button('查看玩家',()=>openDetail(r.code)),button('邀请链接',()=>copyInvite(r.code)));if(r.status==='closed'||r.status==='expired')buttons.append(button('重新开放',()=>confirmAction(r,'reopen')));else buttons.append(button('关闭房间',()=>confirmAction(r,'close'),'close-room'));card.append(top,facts,el('p','room-stage','第 '+r.hand+' 手 · '+r.stage+' · 初始 '+fmt(r.initialStack)),el('p','room-time','创建 '+time(r.created)+' · 活动 '+time(r.activity)),buttons);return card});if(!nodes.length){const empty=el('div','empty');empty.append(el('strong','',rooms.length?'没有符合条件的房间':'还没有好友房'),el('span','',rooms.length?'换个筛选条件或搜索词试试。':'创建好友房后就会显示在这里。'));nodes.push(empty)}$('roomList').replaceChildren(...nodes);if($('roomDetail').open){const r=rooms.find(r=>r.code===detailCode);if(r)renderDetail(r)}}
async function refresh(){if(loading||!token)return;loading=true;$('refresh').disabled=true;clearTimeout(timer);try{const out=await request('/rooms');rooms=out.rooms;$('lastUpdated').textContent='更新 '+time(out.serverTime).split(' ').pop();$('dashboardNotice').textContent='';render();$('dashboard').hidden=false;$('loginPanel').hidden=true;$('logout').hidden=false}catch(e){if(token){$('dashboardNotice').textContent='更新失败，正在显示上次结果。'+e.message;if($('dashboard').hidden)$('loginNotice').textContent='管理验证已通过，但房间列表读取失败。'+e.message;}else if(!$('loginNotice').textContent)$('loginNotice').textContent=e.message}finally{loading=false;$('refresh').disabled=false;if(token)timer=setTimeout(refresh,10000)}}
function renderDetail(r){$('detailTitle').textContent=name(r);$('detailMeta').textContent=r.code+' · '+labels[r.status]+' · 第 '+r.hand+' 手 · '+r.stage;const players=[...r.players].sort((a,b)=>b.net-a.net||a.seat-b.seat);$('detailPlayers').replaceChildren(...players.map((p,i)=>{const row=el('div','detail-player'),info=el('div'),amount=el('div'),who=el('p','name',p.name+(p.host?' · 房主':''));info.append(who,el('p','player-meta',(p.bot?'AI':p.online?'● 在线':'离线')+(p.sittingOut?' · 暂停入局':'')+' · '+p.hands+' 手 · 赢 '+p.wins+' 手'),el('p','player-meta','自动补齐 '+p.autoRefills+' 次 / '+fmt(p.autoTopups)+' · 手动补入 '+fmt(p.topups)+(p.pendingTopup?' · 待入账 '+fmt(p.pendingTopup):'')));const net=el('p','player-net '+(p.net>0?'positive':p.net<0?'negative':'neutral'),(p.net>0?'+':'')+fmt(p.net));net.title='净收益 '+exact(p.net);amount.append(net,el('p','player-stack','筹码 '+fmt(p.stack)));row.append(el('span','rank',i+1),info,amount);return row}))}
async function openDetail(code){try{const out=await request('/rooms/'+code);detailCode=code;renderDetail(out.room);if(!$('roomDetail').open)$('roomDetail').showModal()}catch(e){$('dashboardNotice').textContent=e.message}}
async function copyInvite(code){const u=new URL('online.html',location.href);u.searchParams.set('room',code);try{await navigator.clipboard.writeText(u.href);$('dashboardNotice').textContent='邀请链接已复制。'}catch{$('dashboardNotice').textContent='邀请链接：'+u.href}}
function confirmAction(r,kind){action={code:r.code,kind};$('confirmTitle').textContent=kind==='close'?'关闭这桌？':'重新开放这桌？';$('confirmText').textContent=kind==='close'?(r.playing?'本手将立即暂停，所有玩家断开连接。牌局记录和收益会保留，重新开放后可继续。':'玩家会断开连接。牌局记录和收益会保留，之后可以重新开放。'):'保留原有玩家、筹码和收益，原邀请链接恢复可用。若本手尚未结束，将从原进度继续。';$('confirmRoomName').textContent=name(r)+' · '+r.code;$('confirmNotice').textContent='';$('confirmRoom').textContent=kind==='close'?'确认关闭':'确认开放';$('confirmRoom').className=kind==='close'?'danger':'primary';$('roomConfirm').showModal()}
$('confirmRoom').onclick=async()=>{if(!action)return;const current=action;$('confirmRoom').disabled=true;try{await request('/rooms/'+current.code+'/'+current.kind,{code:current.code});$('roomConfirm').close();action=null;await refresh();$('dashboardNotice').textContent=current.kind==='close'?'房间已关闭，记录已保留。':'房间已重新开放。'}catch(e){$('confirmNotice').textContent=e.message}finally{$('confirmRoom').disabled=false}};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginButton').disabled=true;$('loginNotice').textContent='';try{const out=await request('/login',{key:$('adminKey').value},false);token=out.token;try{sessionStorage.setItem('river-admin-session',token)}catch{}$('adminKey').value='';await refresh()}catch(e){$('loginNotice').textContent=e.message}finally{$('loginButton').disabled=false}};
$('logout').onclick=async()=>{try{await request('/logout',{})}catch{}forget();$('loginNotice').textContent='已退出管理。'};
$('refresh').onclick=refresh;$('roomSearch').oninput=render;$('roomFilter').onchange=render;$('closeDetail').onclick=()=>$('roomDetail').close();for(const id of ['cancelRoom','cancelRoomX'])$(id).onclick=()=>$('roomConfirm').close();document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(timer);else if(token)refresh()});window.addEventListener('pagehide',()=>clearTimeout(timer));if(token)refresh();
})();
