(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='river-duel-v1';let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}let stats={hands:0,wins:0,net:0,...saved.stats};let s=Poker.table(Array.isArray(saved.stacks)&&saved.stacks.every(n=>Number.isInteger(n)&&n>0)&&saved.stacks.reduce((a,b)=>a+b,0)===4000?saved.stacks:[2000,2000],saved.hand||0),serial=0,settled=-1,worker=null,pending=null,sound=false,audio;
try{worker=new Worker('ai-worker.js?v=001a');worker.onmessage=e=>{if(pending&&e.data.id===pending.id){const p=pending;pending=null;clearTimeout(p.watch);setTimeout(()=>aiDone(p.id,e.data.decision),Math.max(0,550-(Date.now()-p.time)))}};worker.onerror=()=>{worker.terminate();worker=null;if(pending){const p=pending;pending=null;clearTimeout(p.watch);setTimeout(()=>aiDone(p.id,Poker.decide(p.view,200)),100)}}}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify({stats,stacks:s.players.map(p=>p.stack),hand:s.hand}))}catch{}}
function beep(){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=520;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.09);o.start();o.stop(audio.currentTime+.1)}catch{}}
function card(c,winning=false){if(c===undefined)return '<div class="card empty" aria-label="等待发牌"></div>';if(c===null)return '<div class="card back" aria-label="AI 暗牌"><span>♠</span></div>';const r=Poker.rank(c),v=({11:'J',12:'Q',13:'K',14:'A'})[r]||r,suit=['♠','♥','♣','♦'][Poker.suit(c)],red=Poker.suit(c)%2===1;return `<div class="card ${red?'red':''} ${winning?'winning':''}" aria-label="${v}${suit}"><span class="corner">${v}<small>${suit}</small></span><span class="suit">${suit}</span><span class="corner bottom">${v}<small>${suit}</small></span></div>`}
function amount(n){return n.toLocaleString('zh-CN')}
function clamp(n){const l=Poker.legal(s,0);return Math.min(l.max,Math.max(Math.min(l.min,l.max),Math.floor(Number(n)||l.min)))}
function setAmount(n){const v=clamp(n);$('raiseRange').value=v;$('raiseAmount').value=v;$('raise').textContent=(v===Poker.legal(s,0).max?'全押至 ':'加注至 ')+amount(v)}
function render(){const done=s.done,l=Poker.legal(s,0),active=!done&&s.turn===0;const show=done&&s.result?.reason==='showdown',best=new Set(show?s.result.best[s.result.winner===-1?0:s.result.winner]:[]);$('handNo').textContent='第 '+s.hand+' 手';$('street').textContent=done?'本手结束':['翻牌前','翻牌','转牌','河牌'][s.street];$('board').innerHTML=Array.from({length:5},(_,i)=>card(s.board[i],best.has(s.board[i]))).join('');$('humanCards').innerHTML=s.players[0].hole.map(c=>card(c,best.has(c))).join('');$('aiCards').innerHTML=s.players[1].hole.map(c=>card(show?c:null,show&&best.has(c))).join('');for(let p=0;p<2;p++){const pre=p?'ai':'human';$(pre+'Stack').textContent=amount(s.players[p].stack);$(pre+'Dealer').hidden=s.button!==p;$(pre+'Bet').textContent=s.players[p].bet?'本轮投入 '+amount(s.players[p].bet):'';$(pre+'Status').textContent=done?'等待下一手':s.players[p].stack===0?'已全押':s.turn===p?(p?'思考中…':'轮到你'):'等待行动';$(pre+'Seat').classList.toggle('active',!done&&s.turn===p)}$('pot').textContent=amount(done?s.result.pot:s.pot);$('potCaption').textContent=done?'已结算':'虚拟筹码';$('handType').textContent=s.board.length>=3?Poker.name(Poker.evaluate([...s.players[0].hole,...s.board])):Poker.rank(s.players[0].hole[0])===Poker.rank(s.players[0].hole[1])?'口袋对子':'你的手牌';$('status').textContent=done?s.log[0]:s.turn===1?'AI 正在思考…':l.need?'轮到你 · 跟注需 '+amount(l.call):'轮到你 · 可以过牌或下注';$('actionPanel').hidden=done;$('resultPanel').hidden=!done;$('fold').disabled=!active;$('call').disabled=!active;$('raise').disabled=!active||!l.raise;$('call').textContent=l.check?'过牌':(l.call===s.players[0].stack?'全押跟注 ':'跟注 ')+amount(l.call);$('raiseRange').min=Math.min(l.min,l.max);$('raiseRange').max=l.max;$('raiseAmount').min=Math.min(l.min,l.max);$('raiseAmount').max=l.max;for(const e of [$('raiseRange'),$('raiseAmount'),...document.querySelectorAll('[data-size]')])e.disabled=!active||!l.raise;setAmount(l.min);$('actionNote').textContent=l.raise?'加注金额为本轮累计投入 · 最小 '+amount(Math.min(l.min,l.max)):'当前只能跟注、过牌或弃牌';$('history').innerHTML=s.log.slice(0,15).map(t=>'<li>'+t+'</li>').join('');$('handsStat').textContent=stats.hands;$('winStat').textContent=stats.hands?Math.round(stats.wins/stats.hands*100)+'%':'—';$('netStat').textContent=(stats.net>=0?'+':'')+amount(stats.net);if(done){const r=s.result,net=r.payouts[0]-s.players[0].total;$('resultBadge').textContent=r.winner===0?'WIN':r.winner===1?'NEXT HAND':'SPLIT POT';$('resultTitle').textContent=r.winner===0?'这一手，你赢了。':r.winner===1?'好牌，下一手再见。':'平局，平分底池。';$('resultDetail').textContent=(show?'你：'+Poker.name(r.values[0])+' · AI：'+Poker.name(r.values[1]):r.winner===0?'AI 弃牌':'你已弃牌')+' · 本手净收益 '+(net>=0?'+':'')+amount(net);$('next').textContent=s.players.some(p=>p.stack===0)?'重新开桌':'下一手'}}
function after(){if(s.done&&settled!==s.hand){settled=s.hand;stats.hands++;if(s.result.winner===0)stats.wins++;stats.net+=s.result.payouts[0]-s.players[0].total;save()}render();if(!s.done&&s.turn===1){const id=++serial,v={...Poker.view(s),difficulty:$('difficulty').value};if(worker){pending={id,view:v,time:Date.now(),watch:setTimeout(()=>{if(pending?.id===id){pending=null;aiDone(id,Poker.decide(v,200))}},5000)};worker.postMessage({id,view:v})}else setTimeout(()=>aiDone(id,Poker.decide(v,250)),550)}}
function aiDone(id,d){if(id!==serial||s.done||s.turn!==1)return;if(!d)d=Poker.decide({...Poker.view(s),difficulty:$('difficulty').value},180);try{Poker.act(s,1,d.kind,d.to)}catch{Poker.act(s,1,Poker.legal(s,1).check?'check':'call')}beep();after()}
function action(kind){if(s.done||s.turn!==0)return;try{Poker.act(s,0,kind,clamp($('raiseAmount').value));beep();after()}catch(e){$('status').textContent=e.message}}
$('fold').onclick=()=>action('fold');$('call').onclick=()=>action(Poker.legal(s,0).check?'check':'call');$('raise').onclick=()=>action('raise');$('raiseRange').oninput=e=>setAmount(e.target.value);$('raiseAmount').onchange=e=>setAmount(e.target.value);for(const b of document.querySelectorAll('[data-size]'))b.onclick=()=>{const l=Poker.legal(s,0),k=b.dataset.size;setAmount(k==='all'?l.max:k==='min'?l.min:s.currentBet+Math.max(s.lastRaise,Math.round((s.pot+l.call)*(k==='half'?.5:1))))};
function next(reset=false){serial++;if(pending){clearTimeout(pending.watch);pending=null}if(reset||s.players.some(p=>p.stack===0)){s=Poker.table();settled=-1;}Poker.begin(s);after()}
$('next').onclick=()=>next();$('restart').onclick=()=>$('restartDialog').showModal();$('cancelRestart').onclick=()=>$('restartDialog').close();$('confirmRestart').onclick=()=>{$('restartDialog').close();next(true)};$('rules').onclick=()=>$('rulesDialog').showModal();$('closeRules').onclick=$('doneRules').onclick=()=>$('rulesDialog').close();$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'音效：开':'音效：关';beep()};$('historyToggle').onclick=()=>{const h=$('history').hidden;$('history').hidden=!h;$('historyToggle').setAttribute('aria-expanded',h?'true':'false');$('historyToggle').textContent=h?'收起':'展开'};$('difficulty').onchange=()=>{$('difficultyHint').textContent={casual:'宽松跟注，适合熟悉规则。',standard:'结合胜率、底池赔率与少量诈唬。',hard:'对大额下注更谨慎，价值下注更积极。'}[$('difficulty').value]};Poker.begin(s);after();
})();
