'use strict';
const assert=require('node:assert/strict');if(!globalThis.crypto)globalThis.crypto=require('node:crypto').webcrypto;
const D=require('./doudizhu.js'),S=require('./table-session.js');
const cards=(...ranks)=>{const used=new Map();return ranks.map(r=>{if(r===16)return 52;if(r===17)return 53;const n=used.get(r)||0;used.set(r,n+1);return (r===15?0:r-2)+n*13})};
const type=(rs,t)=>assert(D.classify(cards(...rs)).some(p=>p.type===t),`${rs} should be ${t}`);
type([3],'single');type([15,15],'pair');type([16,17],'rocket');type([4,4,4,4],'bomb');type([3,3,3,4],'tripleSingle');type([3,3,3,4,4],'triplePair');type([10,11,12,13,14],'straight');type([3,3,4,4,5,5],'pairs');type([3,3,3,4,4,4],'plane');type([3,3,3,4,4,4,8,8],'planeSingle');type([3,3,3,4,4,4,8,8,9,9],'planePair');type([3,3,3,3,8,8],'fourSingle');type([3,3,3,3,8,8,9,9],'fourPair');
for(const rs of [[11,12,13,14,15],[3,4,5,6],[3,3,4,4],[3,3,3,4,4,4,16,17],[3,3,3,3,16,17],[3,3,3,3,4,4,4,4]])assert.equal(D.classify(cards(...rs)).length,0,rs.join(','));
assert.equal(D.classify([0,0]).length,0);assert(D.beats(D.classify(cards(3,3,3,3))[0],D.classify(cards(14))[0]));assert(!D.beats(D.classify(cards(15))[0],D.classify(cards(3,3))[0]));
function ready(g){D.begin(g);D.advanceRunout(g);D.act(g,g.turn,'call');while(g.phase==='rob')D.act(g,g.turn,'norob');while(g.phase==='double')D.act(g,g.turn,'nodouble')}
const g=D.create([2000,2000,2000],['A','B','C']);ready(g);assert.deepEqual(g.players.map(p=>p.cards.length),[20,17,17]);assert.equal(new Set([...g.players.flatMap(p=>p.cards)]).size,54);assert.deepEqual(D.view(g,1).players[0].cards,[]);assert.deepEqual(D.view(g,1).players[2].cards,[]);assert.equal(D.view(g,1).bottom.length,3);
assert.throws(()=>D.act(g,1,'play',g.players[0].cards.slice(0,1)));assert.throws(()=>D.act(g,g.turn,'pass'));
D.act(g,g.turn,'play',[g.players[0].cards.at(-1)]);D.act(g,g.turn,'pass');D.act(g,g.turn,'pass');assert.equal(g.turn,0);assert.equal(g.lastPlay,null);
const b=D.create([2000,2000,2000],['A','B','C']);D.begin(b);D.advanceRunout(b);for(let i=0;i<3;i++)D.act(b,b.turn,'nocall');assert.equal(b.phase,'redeal');D.advanceRunout(b);D.advanceRunout(b);assert.equal(b.attempt,2);assert.equal(b.hand,1);D.act(b,b.turn,'call');while(b.phase==='rob')D.act(b,b.turn,'rob');assert.equal(b.multiplier,8);assert.equal(b.landlord,b.firstCaller);while(b.phase==='double')D.act(b,b.turn,'doubleReveal');assert.equal(b.multiplier,16);assert(D.view(b,1).players.every(p=>p.cards.length));D.begin(b);assert.equal(b.revealMultiplier,false);
for(const landlordWins of [true,false]){const x=D.create(landlordWins?[100,15,35]:[15,35,100],['A','B','C']);ready(x);x.players[0].cards=cards(3);x.players[1].cards=cards(4);x.players[2].cards=cards(5);if(!landlordWins){x.players[0].plays=1;x.turn=1}D.act(x,x.turn,'play',x.players[x.turn].cards);assert.equal(x.result.spring,landlordWins?'春天':'反春天');assert.equal(x.result.net.reduce((a,b)=>a+b,0),0);assert(x.players.every(p=>p.stack>=0));assert.equal(x.result.winners.length,landlordWins?1:2);const r={seats:x.players.map(p=>({name:p.name})),stack:2000,blind:20,game:x,handRecords:[]};S.apply(r);const st=structuredClone(r.stats);S.apply(r);assert.deepEqual(r.stats,st);assert.equal(r.stats.filter(s=>s.autoRefills).length,landlordWins?2:1);assert.equal(S.summary(r).hands,1)}
let steps=0,maxMs=0;const start=Date.now();
for(let n=0;n<250;n++){const x=D.create([2000,2000,2000],['A','B','C']);D.begin(x);let turns=0;while(!x.done){assert(++turns<600,'round terminates');if(x.runout){D.advanceRunout(x);continue}const t=Date.now(),a=D.ai(x,x.turn);maxMs=Math.max(maxMs,Date.now()-t);D.act(x,x.turn,a.kind,a.cards);steps++}assert.equal(x.result.net.reduce((a,b)=>a+b,0),0);assert.equal(new Set(x.events.flatMap(e=>e.cards)).size,x.events.flatMap(e=>e.cards).length);assert(x.players.every(p=>Number.isSafeInteger(p.stack)&&p.stack>=0));assert.equal(x.players.reduce((s,p)=>s+p.stack,0),6000)}
console.log(`Dou Dizhu rules, privacy, bidding, settlement, refill and 250 AI games passed (${steps} moves, ${Date.now()-start}ms, max AI ${maxMs}ms).`);
