(()=>{'use strict';
const D=window.Doudizhu,S=window.TableSession,$=id=>document.getElementById(id),fmt=n=>window.RiverMoney.compact(n),exact=n=>window.RiverMoney.exact(n),query=new URLSearchParams(location.search),practiceKey='river-ddz-practice-v1';
const phaseNames={dealing:'洗牌发牌',redeal:'重新发牌',bid:'叫地主',rob:'抢地主',double:'选择加倍',play:'出牌',result:'本局结算'},actionNames={call:'叫地主',nocall:'不叫',rob:'抢地主',norob:'不抢',double:'加倍',nodouble:'不加倍',doubleReveal:'明牌加倍',pass:'不出',landlord:'成为地主',win:'获胜'};
let state=null,connection=null,isPractice=false,selected=new Set(),selectionStamp='',hintIndex=0,history=[],messages=[],pending=new Map(),reconnectTimer=null,retries=0,closed=false,unread=0,noticeTimer=null,clockOffset=0;
const el=(tag,cls,txt)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(txt!==undefined)n.textContent=txt;return n};
function notice(txt){$('notice').textContent=txt;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{if($('notice').textContent===txt)$('notice').textContent=''},6500)}
function card(c,button=false){const r=c===undefined?'':c>=52?'JOKER':['2','3','4','5','6','7','8','9','10','J','Q','K','A'][c%13],s=c===undefined?'♠':c>=52?'★':['♣','♦','♥','♠'][Math.floor(c/13)],n=el(button?'button':'span','card'+(c===undefined?' back':c>=52?' joker':'')+((c===53||c<39&&c>=13)?' red':''));if(button){n.type='button';n.dataset.card=c;n.setAttribute('aria-label',c===52?'小王':c===53?'大王':s+r);n.setAttribute('aria-pressed',selected.has(c)?'true':'false')}if(c!==undefined){const a=el('span','',undefined);a.append(el('span','rank',r),el('span','corner',s));n.append(a)}n.append(el('span','suit',s));return n}
function saveName(){try{localStorage.setItem('river-ddz-name',$('playerName').value.trim()||'你')}catch{}}
try{$('playerName').value=localStorage.getItem('river-ddz-name')||'你'}catch{}
function showTable(){closed=false;$('lobby').hidden=true;$('tableView').hidden=false;window.RiverAudio?.unlock()}
function send(d){if(!connection){notice('连接尚未恢复，请稍候。');return false}try{connection.send({...d,version:state?.version});return true}catch(e){notice(e.message);return false}}
function feature(d,target){const requestId=crypto.randomUUID();pending.set(requestId,{target,type:d.type});if(!send({...d,requestId})){pending.delete(requestId);return false}return true}
function endConnection(){closed=true;clearTimeout(reconnectTimer);connection?.close();connection=null;for(const entry of pending.values())if(entry.target)$(entry.target).textContent='连接已中断，请重新操作。';pending.clear()}
function startPractice(resume=false){endConnection();isPractice=true;saveName();history=[];messages=[];selected.clear();const r={code:'PRACTICE',gameType:'doudizhu',capacity:3,stack:Number($('initialStack').value),blind:Number($('baseScore').value),host:0,version:0,decisionSeconds:30,autoNext:true,seats:[{name:$('playerName').value.trim()||'你',bot:false,ready:true},{name:'春风 AI',bot:true,ready:true},{name:'留一手 AI',bot:true,ready:true}],game:null,handRecords:[]};S.ensure(r);r.game=D.create(r.seats.map(()=>r.stack),r.seats.map(s=>s.name),r.blind);D.begin(r.game);let saved=null;if(resume===true)try{saved=JSON.parse(localStorage.getItem(practiceKey)||'null')}catch{}const current=saved?.gameType==='doudizhu'&&saved.seats?.length===3&&saved.game?.players?.length===3?saved:r;messages=current.chatMessages||[];connection=localConnect(current);showTable();connection.refresh()}
function localConnect(r){let timer=null,stopped=false;
 const archive=()=>{if(r.game?.done){S.record(r);if(!r.handRecords.some(h=>h.game.hand===r.game.hand))r.handRecords.push({time:Date.now(),game:structuredClone(r.game)});r.handRecords=r.handRecords.slice(-40);S.apply(r)}};
 const canNext=()=>r.autoNext&&r.seats[0].ready&&!r.seats[0].sittingOut;
 function deadline(){archive();r.deadline=r.game?.runout?Date.now()+1200:r.game&&!r.game.done?Date.now()+(r.seats[r.game.turn].bot?850:30000):r.game?.done&&canNext()?Date.now()+8000:null}
 function publish(){if(stopped)return;archive();r.version++;try{localStorage.setItem(practiceKey,JSON.stringify(r))}catch{}receive({type:'history',hands:r.handRecords.map(h=>({time:h.time,game:D.view(h.game,0)}))});receive({type:'state',gameType:'doudizhu',code:r.code,seat:0,host:0,capacity:3,stack:r.stack,blind:r.blind,version:r.version,deadline:r.deadline,serverTime:Date.now(),decisionSeconds:30,autoNext:r.autoNext,seats:r.seats.map(s=>({...s,connected:true})),summary:S.summary(r),game:r.game?D.view(r.game,0):null});clearTimeout(timer);if(r.deadline)timer=setTimeout(alarm,Math.max(0,r.deadline-Date.now()))}
 function alarm(){if(stopped)return;try{if(r.game?.done){if(!canNext()){r.deadline=null;return}D.begin(r.game)}else if(r.game?.runout)D.advanceRunout(r.game);else{const i=r.game.turn,a=r.seats[i].bot?D.ai(r.game,i):D.timeout(r.game,i);if(!r.seats[i].bot){r.seats[i].timeouts=(r.seats[i].timeouts||0)+1;if(r.seats[i].timeouts>=3){r.seats[i].ready=false;r.seats[i].sittingOut=true}}D.act(r.game,i,a.kind,a.cards)}deadline();publish()}catch(e){notice('练习暂停：'+e.message)}}
 deadline();return {refresh:publish,close(){stopped=true;clearTimeout(timer)},send(d){try{if(d.type==='history'){receive({type:'history',hands:r.handRecords.map(h=>({time:h.time,game:D.view(h.game,0)}))});return}if(d.type==='sync'){publish();return}if(['chat','voice'].includes(d.type)){const message={id:crypto.randomUUID(),seat:0,name:r.seats[0].name,time:Date.now(),kind:d.type,text:d.text,audio:d.audio,mime:d.mime,duration:d.duration};r.chatMessages=[...(r.chatMessages||[]),message].filter(m=>m.kind==='chat').slice(-50);receive({type:'chat_message',message});receive({type:'feature_ack',requestId:d.requestId});return}if(d.version!==r.version)throw Error('牌桌已更新，请重新操作');if(d.type==='act'){D.act(r.game,0,d.kind,d.cards);r.seats[0].timeouts=0}else if(d.type==='topup'){S.topup(r,0,d.amount)}else if(d.type==='ready'){if(r.game&&!r.game.done)throw Error('当前牌局未结束');r.seats[0].ready=!r.seats[0].ready;r.seats[0].sittingOut=false;r.seats[0].timeouts=0}else if(d.type==='start'){if(r.game&&!r.game.done)throw Error('当前牌局未结束');r.seats[0].ready=true;r.seats[0].sittingOut=false;r.seats[0].timeouts=0;if(!r.game)r.game=D.create(r.seats.map((_,i)=>S.stack(r,i)),r.seats.map(s=>s.name),r.blind);D.begin(r.game)}else if(d.type==='reset'){if(r.game&&!r.game.done)throw Error('请等待本局结束');S.reset(r);r.seats[0].ready=false}else throw Error('不支持的操作');if(d.type!=='topup'||!r.game||r.game.done)deadline();publish();if(d.requestId)receive({type:'feature_ack',requestId:d.requestId})}catch(e){receive({type:'error',message:e.message})}}}
}
async function createFriend(e){e.preventDefault();saveName();$('friendStart').disabled=true;$('lobbyNotice').textContent='正在开桌…';try{const r=await window.RiverTransport.create({gameType:'doudizhu',capacity:3,name:$('playerName').value,stack:Number($('initialStack').value),blind:Number($('baseScore').value),decisionSeconds:30,autoNext:true});localStorage.setItem('river-ddz-token-'+r.code,r.token);const u=new URL(location.href);u.search='?room='+r.code;location.href=u.href}catch(e){$('lobbyNotice').textContent=e.message}finally{$('friendStart').disabled=false}}
function connectFriend(code){endConnection();isPractice=false;showTable();$('roomTitle').textContent='正在进入牌桌';$('notice').textContent='连接好友房…';let token='';try{token=localStorage.getItem('river-ddz-token-'+code)||''}catch{}
 function connect(){connection=window.RiverTransport.connect({code,token,name:$('playerName').value,onMessage(d){if(d.type==='joined'){token=d.token;try{localStorage.setItem('river-ddz-token-'+code,token)}catch{}retries=0}receive(d)},onClose(){connection=null;if(closed)return;notice('连接中断，正在重连…');reconnectTimer=setTimeout(connect,Math.min(1000*2**retries++,15000))},onError(e){notice(e.message)}})}connect();
}
function receive(d){
 if(d.type==='state'){if(d.gameType!=='doudizhu'){endConnection();notice('这是德州房间，请从首页进入对应牌桌。');return}state=d;clockOffset=d.serverTime-Date.now();$('notice').textContent='';render();return}
 if(d.type==='history'){history=d.hands||[];renderHistory();return}
 if(d.type==='chat_init'){messages=d.messages||[];renderChat();return}
 if(d.type==='chat_message'){if(!messages.some(m=>m.id===d.message.id))messages.push(d.message);messages=messages.slice(-50);if(!$('chatDialog').open){unread++;$('unread').hidden=false}renderChat();bubble(d.message);return}
 if(d.type==='feature_ack'){const entry=pending.get(d.requestId);pending.delete(d.requestId);if(entry?.target)$(entry.target).textContent=entry.type==='topup'?'已确认，本局进行中会在结算后到账。':'已发送';if(entry?.type==='chat')$('chatText').value='';if(entry?.type==='voice')clearVoice();return}
 if(d.type==='error'){notice(d.message);$('chatNotice').textContent=d.message;$('topupNotice').textContent=d.message;pending.clear();return}
 if(d.type==='room_closed'){endConnection();state=null;notice(d.message);$('turnStatus').textContent=d.message;$('actions').replaceChildren(makeButton('返回首页',()=>location.href='index.html','primary'));return}
}
function makeButton(txt,fn,cls,disabled=false){const b=el('button',cls,txt);b.type='button';b.onclick=fn;b.disabled=disabled;return b}
function seatNode(i){const s=state.seats[i],p=state.game?.players[i],g=state.game,winner=g?.done&&g.result.winners.includes(i),active=g&&!g.done&&!g.runout&&g.turn===i,box=el('div','seat-main'),avatar=el('span','avatar'+(g?.landlord===i?' landlord':''),g?.landlord===i?'地主':g?.landlord>=0?'农民':s?.bot?'AI':'友'),info=el('div','');let status=!s?'空位 · 等朋友':!s.connected?'离线':s.sittingOut?'暂停 · 准备后继续':!g?s.ready?'已准备':'未准备':g.runout?'正在发牌':g.done?winner?'胜出 '+(g.result.net[i]>0?'+':'')+fmt(g.result.net[i]):'本局 '+fmt(g.result.net[i]):active?'思考中':g.phase==='play'?'剩 '+p.count+' 张':actionNames[g.lastMoves?.[i]?.kind]||'等待';info.append(el('div','seat-name',s?s.name+(i===state.seat?' · 你':''):'空位'),el('div','seat-amount',s?fmt(p?.stack??state.summary.players[i]?.stack??state.stack):'—'));box.append(avatar,info);const nodes=[box,el('div','seat-status',status)];if(p&&!g.runout&&!g.done)nodes.push(el('span','hand-count',p.count+' 张'+(p.double>1?' · ×2':'')));return {nodes,winner,active}}
function render(){
 const r=state,g=r.game,me=r.seat;window.RiverAudio?.observe(r);$('roomTitle').textContent=isPractice?'斗地主 · 河牌练习室':window.RoomNames.title(r.code);$('roomMeta').textContent=(isPractice?'本机练习':r.code+' · '+r.seats.length+'/3 人')+' · '+(r.seats.every(s=>s.connected)?'已连接':'等朋友上线');$('phaseLabel').textContent=g?phaseNames[g.phase]+(g.phase==='play'&&g.lastPlay?' · '+g.lastPlay.pattern.label:''):'等待开局';$('stakeLabel').textContent='底分 '+fmt(r.blind)+' · ×'+(g?.multiplier||1);$('handNo').textContent='#'+String(g?.hand||0).padStart(4,'0');
 const positions=[[(me+1)%3,'Right'],[(me+2)%3,'Left'],[me,'Self']];for(const [i,pos]of positions){const s=seatNode(i),node=$('seat'+pos);node.replaceChildren(...s.nodes);node.classList.toggle('active',!!s.active);node.classList.toggle('winner',!!s.winner);node.dataset.seat=i;const play=$('play'+pos),move=g?.lastMoves?.[i];play.replaceChildren();if(g?.phase==='play'||g?.done){if(move?.cards?.length)play.append(...move.cards.map(c=>card(c)));else if(move&&actionNames[move.kind])play.append(el('span','played-label',actionNames[move.kind]));if(g?.done&&i!==me&&g.players[i].cards.length){play.replaceChildren(...g.players[i].cards.map(c=>card(c)))}if(g?.done&&i===me)play.replaceChildren()}}
 $('bottomCards').replaceChildren(el('span','bottom-label','底牌'),...(g?.bottom?.length?g.bottom:Array(3).fill(undefined)).map(c=>card(c)));
 const msg=$('tableMessage');msg.replaceChildren();if(!g)msg.append(el('strong','',r.seats.length<3?'等两位老友':'准备开局'),el('small','',r.seats.length<3?'分享邀请链接，或补入 AI':'三人准备后，房主发牌'));else if(g.done){const won=g.result.winners.includes(me);msg.append(el('strong','',won?'这局，你赢了。':'下一局再来。'),el('small','',(g.result.landlordWon?'地主':'农民')+'获胜'+(g.result.spring?' · '+g.result.spring:'')),el('small','',g.result.winningPattern+'收官 · '+(g.result.net[me]>0?'+':'')+fmt(g.result.net[me])))}else if(g.runout)msg.append(el('strong','',g.phase==='redeal'?'无人叫地主':'好戏开场'),el('small','',g.log));else if(g.phase!=='play')msg.append(el('strong','',phaseNames[g.phase]),el('small','',g.players[g.turn].name+'正在选择'));
 const stamp=[r.code,g?.hand,g?.attempt,g?.phase,g?.turn,g?.players[me]?.cards.join(',')].join(':');if(stamp!==selectionStamp){selected.clear();hintIndex=0;selectionStamp=stamp}renderHand();renderActions();renderRanks();renderHistory();tick();
}
function renderHand(){const cs=state.game?.players[state.seat]?.cards||[],container=$('myCards');container.replaceChildren(...cs.map(c=>card(c,true)));const w=container.clientWidth,size=window.innerWidth<=350?38:43,step=Math.min(32,(w-size)/Math.max(1,cs.length-1)),total=step*Math.max(0,cs.length-1)+size,start=(w-total)/2;for(const [i,n]of [...container.children].entries()){n.style.left=start+i*step+'px';n.style.zIndex=i+1;n.classList.toggle('selected',selected.has(Number(n.dataset.card)))}$('handLabel').textContent=cs.length?'我的手牌 · '+cs.length+' 张':'我的手牌';updateSelection()}
function updateSelection(){const g=state?.game,p=selected.size?D.pick([...selected],g?.lastPlay?.pattern):null;$('selectionLabel').textContent=selected.size?(p?p.label+' · '+selected.size+' 张':'已选 '+selected.size+' 张'):'点击选牌 · 滑动连选';for(const n of $('myCards').children){const on=selected.has(Number(n.dataset.card));n.classList.toggle('selected',on);n.setAttribute('aria-pressed',String(on))}const b=$('playAction');if(b)b.disabled=!p||g?.turn!==state.seat}
let drag=null,suppressClick=false;
$('myCards').onpointerdown=e=>{const n=e.target.closest('[data-card]');if(!n||!state?.game?.players[state.seat].cards.length||e.button>0)return;e.preventDefault();const c=Number(n.dataset.card);drag={id:e.pointerId,on:!selected.has(c),visited:new Set([c]),last:[...$('myCards').children].indexOf(n)};if(drag.on)selected.add(c);else selected.delete(c);suppressClick=true;try{$('myCards').setPointerCapture(e.pointerId)}catch{}updateSelection()};
$('myCards').onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;const n=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-card]');if(!n||n.parentElement!==$('myCards'))return;const c=Number(n.dataset.card);if(drag.visited.has(c))return;const nodes=[...$('myCards').children],index=nodes.indexOf(n);for(let j=Math.min(drag.last,index);j<=Math.max(drag.last,index);j++){const value=Number(nodes[j].dataset.card);drag.visited.add(value);if(drag.on)selected.add(value);else selected.delete(value)}drag.last=index;updateSelection()};
for(const type of ['pointerup','pointercancel'])$('myCards').addEventListener(type,()=>{drag=null;setTimeout(()=>suppressClick=false,0)});
$('myCards').onclick=e=>{if(suppressClick)return;const n=e.target.closest('[data-card]');if(!n)return;const c=Number(n.dataset.card);if(selected.has(c))selected.delete(c);else selected.add(c);updateSelection()};$('clearSelection').onclick=()=>{selected.clear();updateSelection()};
function act(kind,cards){return send({type:'act',kind,...(cards?{cards}:{})})}
function renderActions(){const r=state,g=r.game,own=g&&!g.done&&!g.runout&&g.turn===r.seat,a=$('actions');a.replaceChildren();$('actionNote').textContent='';if(!g||g.done){a.append(makeButton(r.seats[r.seat].ready?'取消准备':'准备',()=>send({type:'ready'}),'primary'));if(r.seat===r.host){if(r.seats.length<3)a.append(makeButton('添加 AI',()=>send({type:'addBot'})));a.append(makeButton(g?'开始下一局':'房主发牌',()=>send({type:'start'}),'',r.seats.length<3||r.seats.some(s=>!s.ready||!s.connected)));if(g)a.append(makeButton('重新开桌',()=>send({type:'reset'})))}$('actionNote').textContent=g?'收益累计保留 · 输完自动补齐初始筹码':'三人上线并准备后，房主点击发牌。';return}if(g.runout){a.append(makeButton('正在发牌…',()=>{},'',true));$('actionNote').textContent=g.phase==='redeal'?'三家都不叫，重新随机洗牌。':'54张牌，每人17张，留3张底牌。';return}if(g.phase==='bid'||g.phase==='rob'){a.append(makeButton(g.phase==='bid'?'不叫':'不抢',()=>act(g.phase==='bid'?'nocall':'norob'),'',!own),makeButton(g.phase==='bid'?'叫地主':'抢地主 ×2',()=>act(g.phase==='bid'?'call':'rob'),'primary',!own));$('actionNote').textContent='地主拿到三张底牌，与两位农民对战。';return}if(g.phase==='double'){a.append(makeButton('不加倍',()=>act('nodouble'),'',!own),makeButton('加倍 ×2',()=>act('double'),'primary',!own),makeButton('明牌加倍',()=>act('doubleReveal'),'',!own));$('actionNote').textContent='明牌加倍会向全桌公开你的手牌，额外全桌×2。';return}a.append(makeButton('不出',()=>{selected.clear();act('pass')},'',!own||!g.lastPlay),makeButton('提示',hint,'',!own),makeButton('出牌',()=>act('play',[...selected]),'primary',true));a.lastChild.id='playAction';$('actionNote').textContent=own?g.lastPlay?'选择同牌型、同张数且更大的牌。':'你来领出，选牌后点击出牌。':'留意队友的出牌，等轮到你再行动。';updateSelection()}
function hint(){const g=state.game,options=D.moves(g.players[state.seat].cards,g.lastPlay?.pattern);options.sort((a,b)=>b.cards.length-a.cards.length||a.pattern.main-b.pattern.main);if(!options.length){selected.clear();updateSelection();notice('没有能大过的牌，可以选择不出。');return}selected=new Set(options[hintIndex++%options.length].cards);updateSelection()}
function tick(){if(!state)return;const g=state.game,left=state.deadline?Math.max(0,Math.ceil((state.deadline-Date.now()-clockOffset)/1000)):0;$('countdown').textContent=state.deadline?left+'s':'';$('turnStatus').textContent=!g?'等朋友上线后准备':g.done?state.deadline?'下一局即将开始':'准备好再来一局':g.runout?g.log:g.turn===state.seat?'轮到你行动':g.players[g.turn].name+' · '+(g.phase==='play'?'等待出牌':'正在选择');window.RiverAudio?.countdown(state,left);if(g&&!g.done&&!g.runout){const pos=g.turn===state.seat?'Self':g.turn===(state.seat+1)%3?'Right':'Left',label=$('seat'+pos).querySelector('.seat-status');if(label)label.textContent=(g.turn===state.seat?'思考中':'等待行动')+' '+left+'s'}}
setInterval(tick,250);let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(state)renderHand()},80)});
function renderRanks(){if(!state)return;const ps=[...state.summary.players].map((p,i)=>({...p,seat:i})).sort((a,b)=>b.net-a.net||a.seat-b.seat);$('rankPlayers').replaceChildren(...ps.map((p,i)=>{const row=el('div','rank-row'),info=el('div',''),amount=el('div','rank-money '+(p.net>0?'positive':p.net<0?'negative':''),(p.net>0?'+':'')+fmt(p.net));info.append(el('div','rank-name',p.name+(p.seat===state.seat?' · 你':'')),el('div','rank-meta',p.hands+' 局 · 胜 '+p.wins+' 局'),el('div','rank-meta','自动补齐 '+p.autoRefills+' 次 / '+fmt(p.autoTopups)+' · 补入 '+fmt(p.topups)));amount.title='净收益 '+exact(p.net);amount.append(el('small','','筹码 '+fmt(p.stack)+(p.pendingTopup?' · 待入 '+fmt(p.pendingTopup):'')));row.append(el('span','rank-num',i+1),info,amount);return row}));$('rankTotal').textContent='累计 '+state.summary.hands+' 局 · 初始 '+fmt(state.stack)+' · 底分 '+fmt(state.blind)}
function renderHistory(){const list=$('historyList');if(!history.length){list.replaceChildren(el('p','dialog-note','打完第一局后，记录会出现在这里。'));return}const openHands=new Set([...list.querySelectorAll('details[open]')].map(n=>n.dataset.hand));list.replaceChildren(...history.slice().reverse().map(h=>{const g=h.game,d=el('details',''),summary=el('summary','', '第 '+g.hand+' 局 · '+(g.result.landlordWon?'地主':'农民')+'胜'+(g.result.spring?' · '+g.result.spring:'')),net=g.result.net[state?.seat||0],gain=el('span','history-net',(net>0?'+':'')+fmt(net));summary.append(gain);d.dataset.hand=g.hand;d.open=openHands.has(String(g.hand));const contents=el('div','history-events');contents.append(el('p','dialog-note','底分 '+fmt(g.base)+' · 全桌×'+g.result.multiplier+' · '+g.result.winningPattern+'收官'+(g.result.capped?' · 筹码上限结算':'')));for(const e of g.events){const line=el('div','history-event',g.players[e.seat]?.name+' · '+(e.kind==='play'?e.pattern:actionNames[e.kind]||e.kind)+' ');if(e.cards?.length)line.append(...e.cards.map(c=>card(c)));contents.append(line)}d.append(summary,contents);return d}))}
function renderChat(){const box=$('chatMessages'),nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<70,ids=new Set(messages.map(m=>m.id));for(const row of box.querySelectorAll('.chat-entry'))if(!ids.has(row.dataset.id)){for(const audio of row.querySelectorAll('audio')){audio.pause();if(audio.src.startsWith('blob:'))URL.revokeObjectURL(audio.src)}row.remove()}box.querySelector('.chat-empty')?.remove();if(!messages.length)box.append(el('p','chat-empty','和朋友聊两句，牌桌更热闹。'));const existing=new Set([...box.querySelectorAll('.chat-entry')].map(n=>n.dataset.id));for(const m of messages){if(existing.has(m.id))continue;const row=el('div','chat-entry'+(m.seat===state?.seat?' mine':'')),content=el('div','chat-content');row.dataset.id=m.id;row.append(el('div','chat-who',m.name+' · '+new Date(m.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})));if(m.kind==='voice'){const audio=el('audio');audio.controls=true;audio.preload='none';audio.src='data:'+m.mime+';base64,'+m.audio;content.append(el('span','',Math.round(m.duration)+'秒语音 '),audio)}else content.textContent=m.text;row.append(content);box.append(row)}if(nearBottom)box.scrollTop=box.scrollHeight}
function bubble(m){if(!state)return;const pos=m.seat===state.seat?'self':m.seat===(state.seat+1)%3?'right':'left',n=el('div','bubble '+pos,m.kind==='voice'?'🎙 '+Math.round(m.duration)+'秒语音':m.text.slice(0,38));for(const old of $('bubbles').querySelectorAll('.'+pos))old.remove();$('bubbles').append(n);setTimeout(()=>n.remove(),4500)}
function chat(txt){if(isPractice){$('chatNotice').textContent='练习房消息保存在本机，AI 不会回复。'}feature({type:'chat',text:txt},'chatNotice')}
$('chatForm').onsubmit=e=>{e.preventDefault();const text=$('chatText').value.trim();if(text)chat(text)};for(const txt of ['👍','😎','😂','慢慢来～','快点吧，等到花儿都谢了','好牌！','承让承让'])$('quickChat').append(makeButton(txt,()=>chat(txt)));
let recorder=null,stream=null,voiceBlob=null,voiceMime='',voiceDuration=0,voiceStart=0,voiceTimer=null,recordCancel=false,recordStarting=false,releaseBeforeStart=false,voiceUrl='',chunks=[];
function clearVoice(){if(voiceUrl)URL.revokeObjectURL(voiceUrl);voiceUrl='';voiceBlob=null;$('voicePreview').hidden=true;$('voiceAudio').removeAttribute('src');$('cancelVoice').hidden=true}
function stopVoice(cancel=false){recordCancel=recordCancel||cancel;releaseBeforeStart=true;clearTimeout(voiceTimer);if(recorder?.state==='recording')recorder.stop();else if(!recordStarting)stream?.getTracks().forEach(t=>t.stop())}
async function startVoice(e){if(e.button>0||recordStarting||recorder?.state==='recording')return;e.preventDefault();clearVoice();recordStarting=true;releaseBeforeStart=false;recordCancel=false;$('chatNotice').textContent='正在开启麦克风…';try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('当前浏览器不支持录音');stream=await navigator.mediaDevices.getUserMedia({audio:true});if(releaseBeforeStart){stream.getTracks().forEach(t=>t.stop());$('chatNotice').textContent='麦克风已就绪，请再按住说话。';return}voiceMime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus','audio/webm'].find(m=>MediaRecorder.isTypeSupported(m))||'';recorder=new MediaRecorder(stream,voiceMime?{mimeType:voiceMime,audioBitsPerSecond:32000}:{audioBitsPerSecond:32000});voiceMime=recorder.mimeType.startsWith('audio/mp4')?'audio/mp4':recorder.mimeType;chunks=[];voiceStart=Date.now();recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{voiceDuration=(Date.now()-voiceStart)/1000;stream.getTracks().forEach(t=>t.stop());window.RiverAudio?.record(false);$('recordVoice').textContent='按住说话 · 最长10秒';if(recordCancel||voiceDuration<.3){$('chatNotice').textContent=recordCancel?'已取消录音':'说话太短，请再试一次。';clearVoice();return}voiceBlob=new Blob(chunks,{type:voiceMime});if(voiceBlob.size>98304){$('chatNotice').textContent='语音超过96KB，请缩短后重录。';clearVoice();return}voiceUrl=URL.createObjectURL(voiceBlob);$('voiceAudio').src=voiceUrl;$('voicePreview').hidden=false;$('cancelVoice').hidden=false;$('chatNotice').textContent='可先试听，再发送。'};recorder.start();window.RiverAudio?.record(true);$('recordVoice').textContent='正在录音 · 松开发送前预览';$('cancelVoice').hidden=false;$('chatNotice').textContent='最长10秒，松开后可试听或取消。';voiceTimer=setTimeout(()=>stopVoice(),10000)}catch(e){stream?.getTracks().forEach(t=>t.stop());$('chatNotice').textContent=e.name==='NotAllowedError'?'麦克风权限未开启，可继续文字聊天。':e.message;window.RiverAudio?.record(false)}finally{recordStarting=false}}
$('recordVoice').onpointerdown=startVoice;for(const t of ['pointerup','pointercancel'])window.addEventListener(t,()=>{if(recordStarting||recorder?.state==='recording')stopVoice(t==='pointercancel')});$('cancelVoice').onclick=()=>{stopVoice(true);clearVoice();$('chatNotice').textContent='已取消。'};$('sendVoice').onclick=async()=>{if(!voiceBlob)return;const bytes=new Uint8Array(await voiceBlob.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);feature({type:'voice',audio:btoa(binary),mime:voiceMime,duration:Math.min(10.5,voiceDuration)},'chatNotice')};
function openDialog(id){const d=$(id);if(!d||d.open)return;if(id==='chatDialog'){unread=0;$('unread').hidden=true;renderChat();if(!state)$('chatNotice').textContent='先进入牌桌再聊天。'}if(id==='rankDialog')renderRanks();if(id==='historyDialog'){send({type:'history'});renderHistory()}if(id==='topupDialog'){const unit=state?.blind||20;$('topupAmount').min=unit;$('topupAmount').step=unit;$('topupAmount').value=Math.ceil(1000/unit)*unit;$('topupNotice').textContent=''}d.showModal()}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]'),close=e.target.closest('[data-close]');if(open)openDialog(open.dataset.open);if(close){if(close.closest('dialog').id==='chatDialog')stopVoice(true);close.closest('dialog').close()}});for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{const b=d.getBoundingClientRect();if(e.target===d&&(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)){if(d.id==='chatDialog')stopVoice(true);d.close()}});
$('copyInvite').onclick=async()=>{if(isPractice){notice('练习房在本机运行，创建好友房后可以分享。');$('settingsDialog').close();return}const u=new URL('doudizhu.html',location.href);u.searchParams.set('room',state.code);try{await navigator.clipboard.writeText(u.href);notice('邀请链接已复制。');$('settingsDialog').close()}catch{notice('邀请链接：'+u.href);$('settingsDialog').close()}};$('historyOpen').onclick=()=>openDialog('historyDialog');$('topupOpen').onclick=()=>openDialog('topupDialog');$('topupForm').onsubmit=e=>{e.preventDefault();feature({type:'topup',amount:Number($('topupAmount').value)},'topupNotice')};$('leaveTable').onclick=()=>openDialog('leaveDialog');$('confirmLeave').onclick=()=>{stopVoice(true);endConnection();location.href='doudizhu.html'};
$('practiceStart').onclick=startPractice;$('createForm').onsubmit=createFriend;window.addEventListener('pagehide',()=>{stopVoice(true);endConnection()});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVoice(true);else if(state)send({type:'sync'})});
if(query.has('room')){const code=query.get('room').toUpperCase();if(/^[A-F0-9]{12}$/.test(code))connectFriend(code);else $('lobbyNotice').textContent='房间链接无效，请使用朋友分享的完整链接。'}else if(query.get('practice')==='1')startPractice(true);
})();
