const assert=require('node:assert/strict'),P=require('./poker'),M=require('./multiplayer');
let s=M.create([2000,2000,2000],['A','B','C']);M.begin(s);assert.equal(s.button,0);assert.equal(s.sb,1);assert.equal(s.bb,2);assert.equal(s.turn,0);M.act(s,0,'call');M.act(s,1,'call');assert.equal(s.street,0);assert.equal(s.turn,2);M.act(s,2,'check');assert.equal(s.street,1);assert.equal(s.turn,1);
for(let n=2;n<=6;n++)for(let h=0;h<300;h++){let stacks=Array.from({length:n},()=>Math.floor(Math.random()*300)+1);s=M.create(stacks);const total=stacks.reduce((a,b)=>a+b,0);M.begin(s);let k=0;while(!s.done){assert(++k<200);const i=s.turn,l=M.legal(s),r=Math.random();M.act(s,i,r<.15?'fold':r<.45&&l.raise?'raise':l.check?'check':'call',r<.25?l.max:Math.min(l.max,l.min));assert.equal(s.players.reduce((a,p)=>a+p.stack,0)+s.pot,total);assert(s.players.every(p=>p.stack>=0))}assert.equal(s.result.pots.reduce((a,p)=>a+p.amount,0),s.result.pot);assert.equal(s.result.payouts.reduce((a,b)=>a+b,0),s.result.pot);assert.equal(s.players.reduce((a,p)=>a+p.stack,0),total);assert.equal(new Set([...s.board,...s.burn,...s.players.flatMap(p=>p.hole)]).size,s.board.length+s.burn.length+s.players.flatMap(p=>p.hole).length)}
const c=(r,s=0)=>s*13+r-2;
// Three all-ins: strongest short stack takes main, next hand takes side, unmatched tail returns.
s=M.create([100,200,300],['A','B','C']);M.begin(s);M.act(s,0,'raise',100);M.act(s,1,'raise',200);s.players[0].hole=[c(14,0),c(14,1)];s.players[1].hole=[c(13,0),c(13,1)];s.players[2].hole=[c(12,0),c(12,1)];s.deck=[c(2,3),c(3,3),c(4,2),c(5,2),c(8,1),c(9,3),c(10,2),c(11,3)];M.act(s,2,'call');assert.deepEqual(s.result.payouts,[300,200,0]);assert.deepEqual(s.players.map(p=>p.stack),[300,200,100]);assert.equal(s.result.pots.length,2);
// Short all-in does not reopen the original raiser's action.
s=M.create([1000,50,1000]);M.begin(s);M.act(s,0,'raise',40);M.act(s,1,'raise',50);M.act(s,2,'call');assert.equal(s.turn,0);assert.equal(M.legal(s).raise,false);assert.equal(M.legal(s).call,10);
// Snapshot before showdown never includes other hole cards or deck.
s=M.create([1000,1000,1000]);M.begin(s);const v=M.view(s,0);assert(v.players[0].hole.every(Number.isInteger));assert(v.players[1].hole.every(x=>x===null));assert(!('deck'in v));assert(!('burn'in v));
console.log('PASS: 1,500 multiplayer hands (2–6 seats), chip conservation, blind/action order, side pots, short all-in, card privacy');
