(function(root){'use strict';const P=root.Poker||(typeof require!=='undefined'?require('./poker.js'):null);
const streets=['翻牌前','翻牌','转牌','河牌'];
function create(stacks,names=[],blind=20){return {players:stacks.map((stack,i)=>({stack,name:names[i]||'玩家'+(i+1),hole:[],bet:0,total:0,inHand:false,folded:false,pending:false,raiseAllowed:true})),button:-1,hand:0,blind,board:[],deck:[],burn:[],pot:0,currentBet:0,lastRaise:blind,turn:-1,street:-1,done:true,result:null,log:[]}}
function log(s,t){s.log.unshift(t);s.log.length=Math.min(60,s.log.length)}
function next(s,from,fn){for(let i=1;i<=s.players.length;i++){const p=(from+i)%s.players.length;if(fn(s.players[p],p))return p}return -1}
const live=p=>p.inHand&&!p.folded,able=p=>live(p)&&p.stack>0;
function pay(s,i,n){const p=s.players[i],a=Math.min(p.stack,n);p.stack-=a;p.bet+=a;p.total+=a;s.pot+=a;return a}
function refund(s){const order=s.players.map((p,i)=>({i,total:p.total})).sort((a,b)=>b.total-a.total);if(order[0].total>order[1].total){const d=order[0].total-order[1].total,p=s.players[order[0].i];p.stack+=d;p.total-=d;p.bet=Math.max(0,p.bet-d);s.pot-=d;log(s,p.name+'退回未被跟注的 '+d)}}
function deal(s,n){s.burn.push(s.deck.pop());for(let i=0;i<n;i++)s.board.push(s.deck.pop())}
function settle(s,fold=false){refund(s);const values=s.players.map(p=>live(p)&&!fold?P.evaluate([...p.hole,...s.board]):0),payouts=s.players.map(()=>0),levels=[...new Set(s.players.map(p=>p.total).filter(x=>x>0))].sort((a,b)=>a-b),pots=[];let previous=0;for(const level of levels){const contributors=s.players.map((p,i)=>p.total>=level?i:-1).filter(i=>i>=0),amount=(level-previous)*contributors.length,eligible=contributors.filter(i=>live(s.players[i]));if(!eligible.length)throw Error('无合法边池获胜者');const best=Math.max(...eligible.map(i=>values[i])),winners=eligible.filter(i=>values[i]===best),share=Math.floor(amount/winners.length);for(const i of winners)payouts[i]+=share;let odd=amount%winners.length;for(let k=1;k<=s.players.length&&odd;k++){const i=(s.button+k)%s.players.length;if(winners.includes(i)){payouts[i]++;odd--}}pots.push({amount,winners});previous=level}const total=s.pot;for(let i=0;i<s.players.length;i++)s.players[i].stack+=payouts[i];s.pot=0;s.done=true;s.turn=-1;s.street=4;s.result={reason:fold?'fold':'showdown',pot:total,payouts,values,pots,best:s.players.map(p=>live(p)&&!fold?P.bestFive([...p.hole,...s.board]):[])};const wins=payouts.map((n,i)=>n?`${s.players[i].name} +${n}`:'').filter(Boolean);log(s,'结算 · '+wins.join(' · '))}
function advance(s){const capable=s.players.filter(able);if(capable.length<=1){while(s.board.length<5)deal(s,s.board.length?1:3);settle(s);return}if(s.street===3){settle(s);return}s.street++;deal(s,s.street===1?3:1);s.currentBet=0;s.lastRaise=s.blind;for(const p of s.players){p.bet=0;p.pending=able(p);p.raiseAllowed=true}s.turn=next(s,s.button,able);log(s,streets[s.street]+' · 新一轮下注')}
function progress(s,from){if(s.players.filter(live).length===1){settle(s,true);return}const capable=s.players.filter(able);if(capable.length===1&&capable[0].bet>=s.currentBet){advance(s);return}const todo=next(s,from,p=>able(p)&&p.pending);if(todo<0)advance(s);else s.turn=todo}
function begin(s,rng){if(!s.done)throw Error('请完成当前牌局');if(s.players.filter(p=>p.stack>0).length<2)throw Error('至少需要两名有筹码的玩家');s.hand++;s.button=next(s,s.button,p=>p.stack>0);s.done=false;s.street=0;s.board=[];s.burn=[];s.result=null;s.deck=P.shuffled(rng);s.pot=0;s.currentBet=s.blind;s.lastRaise=s.blind;for(const p of s.players){p.hole=[];p.bet=0;p.total=0;p.inHand=p.stack>0;p.folded=false;p.pending=p.inHand;p.raiseAllowed=true}const count=s.players.filter(p=>p.inHand).length,sb=count===2?s.button:next(s,s.button,p=>p.inHand),bb=next(s,sb,p=>p.inHand);for(let r=0;r<2;r++){let i=s.button;for(let n=0;n<count;n++){i=next(s,i,p=>p.inHand);s.players[i].hole.push(s.deck.pop())}}pay(s,sb,Math.floor(s.blind/2));pay(s,bb,s.blind);s.sb=sb;s.bb=bb;s.turn=count===2?sb:next(s,bb,able);log(s,'第 '+s.hand+' 手 · '+s.players[s.button].name+'为庄家');progress(s,(s.turn+s.players.length-1)%s.players.length);return s}
function legal(s,i=s.turn){const p=s.players[i];if(!p)return {need:0,call:0,check:false,max:0,min:0,raise:false};const need=Math.max(0,s.currentBet-p.bet),max=p.bet+p.stack,min=s.currentBet+s.lastRaise;return {need,call:Math.min(need,p.stack),check:need===0,max,min,raise:!s.done&&able(p)&&p.raiseAllowed&&max>s.currentBet&&s.players.some((q,j)=>j!==i&&able(q))}}
function act(s,i,kind,to){if(s.done||s.turn!==i||!able(s.players[i]))throw Error('现在不是你的行动轮次');const p=s.players[i],l=legal(s,i);if(kind==='fold'){p.folded=true;log(s,p.name+'弃牌')}else if(kind==='check'){if(!l.check)throw Error('需要跟注');log(s,p.name+'过牌')}else if(kind==='call'){pay(s,i,l.call);log(s,p.name+(p.stack===0?'全押跟注 ':'跟注 ')+l.call)}else if(kind==='raise'){to=Number(to);if(!Number.isSafeInteger(to)||!l.raise||to<=s.currentBet||to>l.max||(to<l.min&&to!==l.max))throw Error('加注金额不合法');const increase=to-s.currentBet;pay(s,i,to-p.bet);if(increase>=s.lastRaise){s.lastRaise=increase;for(const q of s.players)if(able(q)){q.pending=true;q.raiseAllowed=true}}else for(const q of s.players)if(able(q)&&q.bet<to)q.pending=true;s.currentBet=to;log(s,p.name+(p.stack===0?'全押至 ':'加注至 ')+to)}else throw Error('未知行动');p.pending=false;p.raiseAllowed=false;progress(s,i)}
function view(s,seat){return {players:s.players.map((p,i)=>({name:p.name,stack:p.stack,bet:p.bet,total:p.total,folded:p.folded,inHand:p.inHand,hole:i===seat||s.done&&s.result?.reason==='showdown'&&live(p)?[...p.hole]:p.hole.map(()=>null)})),button:s.button,sb:s.sb,bb:s.bb,hand:s.hand,street:s.street,turn:s.turn,currentBet:s.currentBet,lastRaise:s.lastRaise,board:[...s.board],pot:s.pot,done:s.done,result:s.result,log:[...s.log],legal:legal(s,seat)}}
function ai(s,seat,rng=Math.random){const me=s.players[seat],l=legal(s,seat),v={hole:me.hole,board:s.board,stack:me.stack,otherStack:Math.max(...s.players.filter((p,i)=>i!==seat&&live(p)).map(p=>p.stack)),pot:s.pot,bet:me.bet,currentBet:s.currentBet,street:s.street,legal:l,pressure:l.need/Math.max(20,s.pot)};const eq=P.equity(v,220,rng)**Math.max(1,s.players.filter(live).length-1),odds=l.call/Math.max(1,s.pot+l.call),r=rng();if(l.raise&&(eq>.64&&r<.72||eq<.38&&r<.035)){const to=Math.min(l.max,Math.max(l.min,s.currentBet+Math.round(Math.max(s.blind,s.pot*.55)/s.blind)*s.blind));return {kind:'raise',to}}return {kind:l.need&&eq<odds+.025?'fold':l.check?'check':'call'}}
const api={create,begin,act,legal,view,ai};root.MultiPoker=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
