(function(root){'use strict';
const BASE=759375,NAMES=['高牌','一对','两对','三条','顺子','同花','葫芦','四条','同花顺'];
const rank=c=>c%13+2,suit=c=>Math.floor(c/13);
function score(cat,k){let v=cat;for(let i=0;i<5;i++)v=v*15+(k[i]||0);return v}
function straight(mask){for(let h=14;h>=6;h--)if(((mask>>(h-4))&31)===31)return h;return (mask&(1<<14))&&(mask&60)===60?5:0}
function evaluate(cards){const count=new Uint8Array(15),suits=[[],[],[],[]];let mask=0;for(const c of cards){let r=rank(c);count[r]++;mask|=1<<r;suits[suit(c)].push(r)}let flush=suits.find(a=>a.length>=5);if(flush){flush.sort((a,b)=>b-a);const sf=straight(flush.reduce((m,r)=>m|(1<<r),0));if(sf)return score(8,[sf])}const groups=[];for(let r=14;r>=2;r--)if(count[r])groups.push(r);const quads=groups.filter(r=>count[r]===4),trips=groups.filter(r=>count[r]>=3),pairs=groups.filter(r=>count[r]>=2);if(quads.length)return score(7,[quads[0],groups.find(r=>r!==quads[0])]);if(trips.length){const pair=pairs.find(r=>r!==trips[0]);if(pair)return score(6,[trips[0],pair])}if(flush)return score(5,flush.slice(0,5));const st=straight(mask);if(st)return score(4,[st]);if(trips.length)return score(3,[trips[0],...groups.filter(r=>r!==trips[0]).slice(0,2)]);if(pairs.length>=2)return score(2,[pairs[0],pairs[1],groups.find(r=>r!==pairs[0]&&r!==pairs[1])]);if(pairs.length)return score(1,[pairs[0],...groups.filter(r=>r!==pairs[0]).slice(0,3)]);return score(0,groups.slice(0,5))}
function name(v){return Math.floor(v/BASE)===8&&Math.floor((v%BASE)/50625)===14?'皇家同花顺':NAMES[Math.floor(v/BASE)]}
function bestFive(cards){if(cards.length<5)return cards;let best=-1,out=[];for(let a=0;a<cards.length-4;a++)for(let b=a+1;b<cards.length-3;b++)for(let c=b+1;c<cards.length-2;c++)for(let d=c+1;d<cards.length-1;d++)for(let e=d+1;e<cards.length;e++){const hand=[cards[a],cards[b],cards[c],cards[d],cards[e]],v=evaluate(hand);if(v>best){best=v;out=hand}}return out}
function secureRandom(){if(typeof crypto!=='undefined'&&crypto.getRandomValues){const x=new Uint32Array(1);crypto.getRandomValues(x);return x[0]/4294967296}return Math.random()}
function shuffled(rng=secureRandom){const d=Array.from({length:52},(_,i)=>i);for(let i=51;i>0;i--){const j=Math.floor(rng()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function table(stacks=[2000,2000],hand=0){return {players:stacks.map(stack=>({stack,hole:[],bet:0,total:0,acted:false,canRaise:true})),hand,button:0,street:-1,turn:0,currentBet:0,lastRaise:20,pot:0,board:[],deck:[],log:[],done:true,result:null,burn:[]}}
function log(s,text){s.log.unshift(text);s.log=s.log.slice(0,60)}
function pay(s,p,amount){const a=Math.min(s.players[p].stack,amount);s.players[p].stack-=a;s.players[p].bet+=a;s.players[p].total+=a;s.pot+=a;return a}
function refund(s){const [a,b]=s.players;if(a.total===b.total)return;const p=a.total>b.total?a:b,d=Math.abs(a.total-b.total);p.stack+=d;p.total-=d;p.bet=Math.max(0,p.bet-d);s.pot-=d;log(s,'未被跟注的 '+d+' 筹码退回')}
function deal(s,n){s.burn.push(s.deck.pop());for(let i=0;i<n;i++)s.board.push(s.deck.pop())}
function showdown(s){refund(s);const values=s.players.map(p=>evaluate([...p.hole,...s.board])),winner=values[0]===values[1]?-1:values[0]>values[1]?0:1,pot=s.pot;let payouts=[0,0];if(winner===-1){payouts=[Math.floor(pot/2),Math.floor(pot/2)];payouts[1-s.button]+=pot%2}else payouts[winner]=pot;for(let p=0;p<2;p++)s.players[p].stack+=payouts[p];s.pot=0;s.done=true;s.street=4;s.result={winner,reason:'showdown',pot,payouts,values,best:s.players.map(p=>bestFive([...p.hole,...s.board]))};log(s,winner===-1?'平局，平分底池':(winner===0?'你':'AI')+'凭'+name(values[winner])+'赢得 '+pot)}
function advance(s){if(s.players.some(p=>p.stack===0)){refund(s);while(s.board.length<5)deal(s,s.board.length===0?3:1);showdown(s);return}if(s.street===3){showdown(s);return}s.street++;deal(s,s.street===1?3:1);for(const p of s.players){p.bet=0;p.acted=false;p.canRaise=true}s.currentBet=0;s.lastRaise=20;s.turn=1-s.button;log(s,['翻牌前','翻牌','转牌','河牌'][s.street]+' · 新一轮下注')}
function begin(s,rng=secureRandom){if(!s.done)throw Error('请先完成当前手牌');if(s.players.some(p=>p.stack<=0))throw Error('对局已结束');s.hand++;s.button=(s.hand-1)%2;s.street=0;s.deck=shuffled(rng);s.board=[];s.burn=[];s.result=null;s.done=false;s.pot=0;s.lastRaise=20;for(const p of s.players){p.hole=[];p.bet=0;p.total=0;p.acted=false;p.canRaise=true}for(let i=0;i<2;i++)for(let p=0;p<2;p++)s.players[p].hole.push(s.deck.pop());pay(s,s.button,10);pay(s,1-s.button,20);s.currentBet=Math.max(...s.players.map(p=>p.bet));s.turn=s.button;log(s,'第 '+s.hand+' 手 · '+(s.button===0?'你':'AI')+'为庄家 / 小盲');if(s.players[s.turn].stack===0&&s.players[1-s.turn].bet>=s.players[s.turn].bet)advance(s);else if(s.players[s.turn].stack===0)s.turn=1-s.turn;return s}
function legal(s,p=s.turn){const me=s.players[p],other=s.players[1-p],need=Math.max(0,s.currentBet-me.bet),max=me.stack+me.bet,min=s.currentBet+(s.currentBet?s.lastRaise:20);return {need,call:Math.min(need,me.stack),check:need===0,max,min,raise:!s.done&&me.stack>0&&other.stack>0&&me.canRaise&&max>s.currentBet,shortAllIn:max<min}}
function act(s,p,kind,to){if(s.done||s.turn!==p||s.players[p].stack===0)throw Error('当前不能行动');const me=s.players[p],l=legal(s,p),who=p===0?'你':'AI';if(kind==='fold'){refund(s);const winner=1-p,pot=s.pot;s.players[winner].stack+=pot;s.pot=0;s.done=true;s.street=4;s.result={winner,reason:'fold',pot,payouts:[winner===0?pot:0,winner===1?pot:0]};log(s,who+'弃牌，'+(winner===0?'你':'AI')+'赢得 '+pot);return}
 if(kind==='check'){if(!l.check)throw Error('需要跟注，不能过牌');log(s,who+'过牌')}
 else if(kind==='call'){pay(s,p,l.call);log(s,who+(l.call===0?'过牌':me.stack===0?'全押跟注 '+l.call:'跟注 '+l.call))}
 else if(kind==='raise'){to=Math.floor(Number(to));if(!l.raise||!Number.isFinite(to)||to<=s.currentBet||to>l.max||(to<l.min&&to!==l.max))throw Error('加注额不合法');const increase=to-s.currentBet,full=increase>=s.lastRaise;pay(s,p,to-me.bet);if(full){s.lastRaise=increase;for(const player of s.players){player.acted=false;player.canRaise=true}}s.currentBet=to;log(s,who+(me.stack===0?'全押至 ':l.need===0&&me.bet===to&&to===increase?'下注 ': '加注至 ')+to)}else throw Error('未知行动');me.acted=true;me.canRaise=false;const other=s.players[1-p];if(other.stack===0&&me.bet>=other.bet){advance(s);return}if(me.stack===0&&other.bet>=me.bet){advance(s);return}if(s.players.every(q=>q.acted)&&me.bet===other.bet){advance(s);return}s.turn=1-p}
function view(s,p=1){const l=legal(s,p);return {hole:[...s.players[p].hole],board:[...s.board],stack:s.players[p].stack,otherStack:s.players[1-p].stack,pot:s.pot,bet:s.players[p].bet,currentBet:s.currentBet,street:s.street,button:s.button===p,legal:l,pressure:l.need/Math.max(20,s.pot),opponentRaises:s.opponentRaises||0}}
function preStrength(hole){const a=rank(hole[0]),b=rank(hole[1]),hi=Math.max(a,b),lo=Math.min(a,b);return Math.min(1,a===b?.48+(a-2)*.04:.12+(hi+lo-4)*.019+(suit(hole[0])===suit(hole[1])?.07:0)+(hi-lo<=2?.07:0))}
function equity(v,samples=500,rng=Math.random){const known=new Set([...v.hole,...v.board]),deck=Array.from({length:52},(_,i)=>i).filter(c=>!known.has(c));let sum=0;for(let n=0;n<samples;n++){let cards,opponent;for(let attempt=0;attempt<9;attempt++){cards=[...deck];for(let i=0;i<2;i++){let j=i+Math.floor(rng()*(cards.length-i));[cards[i],cards[j]]=[cards[j],cards[i]]}opponent=cards.slice(0,2);const weight=v.pressure>.18?.25+.75*preStrength(opponent):1;if(rng()<weight)break}const board=[...v.board];for(let i=2;board.length<5;i++){let j=i+Math.floor(rng()*(cards.length-i));[cards[i],cards[j]]=[cards[j],cards[i]];board.push(cards[i])}const a=evaluate([...v.hole,...board]),b=evaluate([...opponent,...board]);sum+=a>b?1:a===b?.5:0}return sum/samples}
function decide(v,samples=600,rng=Math.random){const eq=equity(v,samples,rng),l=v.legal,odds=l.call/Math.max(1,v.pot+l.call);const margin=v.difficulty==='casual'?-.09:v.difficulty==='hard'?.055:.025;const random=rng();let bluff=eq<.48&&random<(v.street>0?.11:.05);let wantsRaise=l.raise&&((eq>.7&&random<.8)||(eq>.57&&l.need===0&&random<.7)||bluff);if(l.need>0&&eq<odds+margin&&!wantsRaise)return {kind:'fold',equity:eq};if(wantsRaise){const add=Math.max(20,Math.round((v.pot+l.call)*(eq>.78?.85:.52)/10)*10),to=Math.min(l.max,Math.max(l.min,v.currentBet+add));if(to>v.currentBet&&(to>=l.min||to===l.max))return {kind:'raise',to,equity:eq}}return {kind:l.check?'check':'call',equity:eq}}
const api={rank,suit,evaluate,name,bestFive,shuffled,table,begin,act,legal,view,equity,decide,BASE};root.Poker=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
