/* Practice and friend rooms share the same rules and replay format. */
(()=>{'use strict';if(new URLSearchParams(location.search).get('practice')!=='1')return;
let room,game,version=0,timer,deadline,handlers,disposed=false,timeouts=0;
const names=['你','River AI','Sage AI','Nova AI','Atlas AI','Echo AI'];
function emit(){if(!handlers||disposed)return;handlers.onMessage({type:'state',code:room.code,seat:0,host:0,capacity:room.capacity,stack:room.stack,blind:room.blind,decisionSeconds:room.decisionSeconds,autoNext:room.autoNext,version:++version,deadline,serverTime:Date.now(),seats:room.seats.map(s=>({...s,connected:true})),game:game?MultiPoker.view(game,0):null})}
function begin(){if(!game)game=MultiPoker.create(room.seats.map(()=>room.stack),room.seats.map(s=>s.name),room.blind);game.pacedRunout=true;MultiPoker.begin(game)}
function canContinue(){return room.autoNext&&game?.done&&!room.seats[0].sittingOut&&game.players[0].stack>0&&game.players.filter(p=>p.stack>0).length>1}
function schedule(){clearTimeout(timer);deadline=game&&!game.done?Date.now()+(game.runout?2000:game.turn?850:room.decisionSeconds*1000):canContinue()?Date.now()+5000:null;emit();if(!deadline)return;timer=setTimeout(()=>{if(disposed)return;try{if(game.done)begin();else if(game.runout)MultiPoker.advanceRunout(game);else{const i=game.turn,l=MultiPoker.legal(game,i),d=i?MultiPoker.ai(game,i):{kind:l.check?'check':'fold'};if(!i&&++timeouts>=3)room.seats[0].sittingOut=true;MultiPoker.act(game,i,d.kind,d.to)}schedule()}catch(e){handlers.onMessage({type:'error',message:e.message})}},Math.max(0,deadline-Date.now()))}
window.RiverTransport={available:true,provider:'local',async create(d){if(!Number.isInteger(d.capacity)||d.capacity<2||d.capacity>12)throw Error('座位数量请输入 2～12 的整数。');disposed=false;timeouts=0;room={code:'P'+Date.now().toString(16).toUpperCase(),capacity:d.capacity,stack:d.stack,blind:d.blind,decisionSeconds:[15,20,30].includes(d.decisionSeconds)?d.decisionSeconds:15,autoNext:d.autoNext!==false,seats:Array.from({length:d.capacity},(_,i)=>({name:i?(names[i]||'牌手 '+i+' AI'):d.name,bot:i>0,ready:true}))};game=null;return {code:room.code,token:'local'}},connect(h){handlers=h;disposed=false;queueMicrotask(()=>{h.onMessage({type:'joined',token:'local'});begin();schedule()});return {send(d){try{if(d.type==='ready'){room.seats[0].sittingOut=false;timeouts=0;if(game?.done)game.players[0].sittingOut=false;schedule()}else if(d.type==='start'){room.seats[0].sittingOut=false;timeouts=0;begin();schedule()}else if(d.type==='act'){MultiPoker.act(game,0,d.kind,d.to);timeouts=0;schedule()}else if(d.type==='reset'){clearTimeout(timer);deadline=null;game=null;timeouts=0;room.seats[0].sittingOut=false;begin();schedule()}}catch(e){h.onMessage({type:'error',message:e.message});emit()}},close(){disposed=true;clearTimeout(timer)}}}};
})();
