import assert from 'node:assert/strict';import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
const mf=new Miniflare(convertV4MiniflareOptions({modules:true,scriptPath:'.room-test-dist/worker.js',compatibilityDate:'2026-10-03',host:'127.0.0.1',port:0,durableObjects:{ROOMS:{className:'PokerRoom',useSQLite:true}},bindings:{ALLOWED_ORIGINS:'https://liangxingya-svg.github.io'}}));
await mf.ready;const fetch=(...args)=>mf.dispatchFetch(...args);
const base='http://127.0.0.1:8787',origin='https://liangxingya-svg.github.io';
const wait=(fn,timeout=12000)=>new Promise((resolve,reject)=>{const end=Date.now()+timeout;const timer=setInterval(()=>{const value=fn();if(value){clearInterval(timer);resolve(value)}else if(Date.now()>end){clearInterval(timer);reject(Error('Timeout'))}},20)});
assert.equal((await fetch(base+'/api/health')).status,200);assert.equal((await fetch(base+'/api/health',{headers:{Origin:'https://wrong.example'}})).status,403);
const response=await fetch(base+'/api/rooms',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({name:'房主',capacity:4,stack:2000,blind:20})});assert.equal(response.status,201);const room=await response.json();
async function connect(name,token){const response=await fetch(base+'/api/rooms/'+room.code+'/ws',{headers:{Origin:origin,Upgrade:'websocket'}});assert.equal(response.status,101);const ws=response.webSocket;const client={ws,state:null,token:null,errors:[]};ws.addEventListener('message',e=>{if(String(e.data)==='pong')return;const d=JSON.parse(e.data);if(d.type==='state')client.state=d;if(d.type==='joined')client.token=d.token;if(d.type==='error')client.errors.push(d.message)});ws.accept();ws.send(JSON.stringify({type:'join',name,token}));await wait(()=>client.state&&client.token);return client}
let host=await connect('房主',room.token),friend=await connect('朋友');await wait(()=>host.state.seats.length===2);assert.equal(host.token,room.token);
async function send(c,type,extra={}){const version=c.state.version;c.ws.send(JSON.stringify({type,version,...extra}));await wait(()=>c.state.version>version||c.errors.length);assert.equal(c.errors.length,0,c.errors.join(','));return c.state}
await send(host,'ready');await wait(()=>friend.state.version===host.state.version);await send(friend,'ready');await wait(()=>host.state.version===friend.state.version);await send(host,'addBot');await wait(()=>friend.state.version===host.state.version);await send(host,'start');await wait(()=>friend.state.game?.hand===1);assert(host.state.game.players[0].hole.every(Number.isInteger));assert(host.state.game.players[1].hole.every(x=>x===null));assert(friend.state.game.players[0].hole.every(x=>x===null));assert(friend.state.game.players[1].hole.every(Number.isInteger));assert(!JSON.stringify(host.state).includes(friend.token));assert(!JSON.stringify(friend.state).includes(room.token));
const previous=structuredClone(friend.state.game.players[1].hole);friend.ws.close();friend=await connect('朋友',friend.token);assert.deepEqual(friend.state.game.players[1].hole,previous);assert.equal(friend.state.seat,1);
let steps=0;while(!host.state.game.done){assert(++steps<100);await wait(()=>host.state.version===friend.state.version);const turn=host.state.game.turn,version=host.state.version;if(turn===2){await wait(()=>host.state.version>version);continue}const client=turn===0?host:friend,l=client.state.game.legal;await send(client,'act',{kind:l.check?'check':'call'});await wait(()=>host.state.version===friend.state.version)}assert.equal(host.state.game.players.reduce((a,p)=>a+p.stack,0),6000);assert(host.state.game.done);assert.deepEqual(host.state.game.result,friend.state.game.result);assert(host.state.seats.filter(s=>!s.bot).every(s=>!s.ready));
// A stale action must not be applied twice.
const version=host.state.version;host.ws.send(JSON.stringify({type:'ready',version:version-1}));await wait(()=>host.errors.length);assert.equal(host.state.version,version);assert(host.errors[0].includes('牌桌已更新'));host.ws.close();friend.ws.close();
console.log('PASS: real Workers runtime + SQLite room, two WebSocket clients, readiness, AI alarm, hidden-card isolation, reconnect same seat/cards, shared settlement, stale-message rejection');

await mf.dispose();
