const fs=require('fs'),vm=require('vm'),assert=require('assert');
function element(){return {value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,style:{},dataset:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},setAttribute(){},querySelector(){return element()},querySelectorAll(){return []},focus(){},scrollIntoView(){},showModal(){},close(){}}}
const els={};for(const m of fs.readFileSync('online.html','utf8').matchAll(/id="([^"]+)"/g))els[m[1]]=element();
const capacity=Number(process.env.CAPACITY||6);els.capacity.value=String(capacity);els.startingStack.value='2000';els.blinds.value='20';
const pending=new Map(),storage=new Map();let tid=0;
const ctx={console,URL,URLSearchParams,Math,Date,Number,String,Array,Set,JSON,Promise,queueMicrotask,Error,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},location:{search:'?practice=1',href:'https://example.test/online.html?practice=1'},history:{replaceState(){}},document:{getElementById:id=>{assert(els[id],'missing '+id);return els[id]},querySelectorAll:()=>[],body:{classList:element().classList},addEventListener(){}},navigator:{},setTimeout:f=>{pending.set(++tid,f);return tid},clearTimeout:id=>pending.delete(id),setInterval(){},addEventListener(){}};ctx.window=ctx;vm.createContext(ctx);
for(const file of ['poker.js','multiplayer.js','practice.js','online.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
(async()=>{await els.roomForm.onsubmit({preventDefault(){}});await Promise.resolve();assert.equal(els.lobby.hidden,true);assert.equal(els.roomArea.hidden,false);assert(!els.startHand.disabled);assert.equal(els.myHandName.textContent,'等待发牌');
for(let h=0;h<8;h++){els.startHand.onclick();let steps=0;while(els.onlineResult.hidden){assert(++steps<300);if(!els.onlineCall.disabled)els.onlineCall.onclick();else {const [id,f]=pending.entries().next().value||[];assert(f,'AI timer missing');pending.delete(id);f()}}assert(els.onlineResultDetail.textContent.includes('本手净收益'));assert(!els.startHand.disabled)}
const journal=JSON.parse(storage.get('river-hand-journal'));assert.equal(journal.length,8);assert(journal.every(h=>h.mode==='practice'&&h.players.length===capacity));assert.equal(new Set(journal.map(h=>h.id)).size,8);assert.equal(els.invite.hidden,true);assert.equal(els.ready.hidden,true);
els.startHand.onclick();while(els.onlineCall.disabled){const [id,f]=pending.entries().next().value;pending.delete(id);f()}els.onlineRaiseAmount.value=String(Number(els.onlineRaiseRange.max));els.onlineRaiseAmount.onchange({target:els.onlineRaiseAmount});const selected=els.onlineRaiseAmount.value;await ctx.RiverTransport;/* Re-render via unchanged table update. */
els.ready.onclick();assert.equal(els.onlineRaiseAmount.value,selected,'sync must preserve selected raise');els.onlineFold.onclick();
console.log('PASS: local practice, 8 completed hands, private cards, journal, next-hand availability, raise selection retained');
})().catch(e=>{console.error(e);process.exitCode=1});
