const fs=require('fs'),vm=require('vm'),assert=require('assert');
function element(){return {value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,style:{},dataset:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},setAttribute(){},querySelector(){return element()},querySelectorAll(){return []},focus(){},scrollIntoView(){},showModal(){},close(){}}}
const els={};for(const m of fs.readFileSync('online.html','utf8').matchAll(/id="([^"]+)"/g))els[m[1]]=element();
const capacity=Number(process.env.CAPACITY||6);els.capacity.value=String(capacity);els.startingStack.value='2000';els.blinds.value='20';els.decisionSeconds.value='15';els.autoNext.value='true';els.journalOutcome.value='all';
const presetButtons=['a','b','c','d','all'].map(k=>{const e=element();e.dataset.onlineSize=k;return e}),stageButtons=[0,1,2,3,4].map(k=>{const e=element();e.dataset.replayStage=String(k);return e});let replayButtons=[];
function queryAll(selector){if(selector==='[data-online-size]')return presetButtons;if(selector==='[data-replay-stage]')return stageButtons;if(selector==='[data-replay-id]'){replayButtons=[...els.handJournal.innerHTML.matchAll(/data-replay-id="([^"]+)"/g)].map(m=>{const e=element();e.dataset.replayId=m[1].replaceAll('&quot;','"').replaceAll('&amp;','&');return e});return replayButtons}return []}
const pending=new Map(),storage=new Map();let tid=0;
const ctx={console,URL,URLSearchParams,Math,Date,Number,String,Array,Set,JSON,Promise,queueMicrotask,Error,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},location:{search:'?practice=1',href:'https://example.test/online.html?practice=1'},history:{replaceState(){}},document:{getElementById:id=>{assert(els[id],'missing '+id);return els[id]},querySelectorAll:queryAll,body:{classList:element().classList},addEventListener(){}},navigator:{},setTimeout:f=>{pending.set(++tid,f);return tid},clearTimeout:id=>pending.delete(id),setInterval(){},addEventListener(){}};ctx.window=ctx;vm.createContext(ctx);
for(const file of ['poker.js','multiplayer.js','practice.js','online.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
(async()=>{await els.roomForm.onsubmit({preventDefault(){}});await Promise.resolve();assert.equal(els.lobby.hidden,true);assert.equal(els.roomArea.hidden,false);assert(els.startHand.disabled);assert.notEqual(els.myHandName.textContent,'等待发牌');assert(!els.seats.innerHTML.includes('undefined'),'all seat names and positions must exist');assert.equal((els.seats.innerHTML.match(/class="online-seat /g)||[]).length,capacity);
for(let h=0;h<8;h++){if(h>0){if(els.startHand.disabled){const [id,f]=pending.entries().next().value||[];assert(f,'next-hand timer missing');pending.delete(id);f()}else els.startHand.onclick()};let steps=0;while(els.onlineResult.hidden){assert(++steps<300);if(!els.onlineCall.disabled)els.onlineCall.onclick();else {const [id,f]=pending.entries().next().value||[];assert(f,'AI timer missing');pending.delete(id);f()}}assert(els.onlineResultDetail.textContent.includes('本手净收益'));}
const journal=JSON.parse(storage.get('river-hand-journal'));assert.equal(journal.length,8);assert(journal.every(h=>h.mode==='practice'&&h.players.length===capacity&&h.events.length>2&&h.events.at(-1).done));assert.equal(new Set(journal.map(h=>h.id)).size,8);assert(replayButtons.length);replayButtons[0].onclick();assert.equal(els.replayStage.textContent,'结算');els.replayFirst.onclick();assert.equal(els.replayStage.textContent,'翻牌前');assert(els.replayPlayers.innerHTML.includes('暗牌'));els.replayNext.onclick();assert(els.replayProgress.textContent.startsWith('2 /'));els.replayLast.onclick();assert.equal(els.replayStage.textContent,'结算');els.closeReplay.onclick();assert.equal(els.invite.hidden,true);assert.equal(els.ready.hidden,true);
els.confirmOnlineReset.onclick();let turns=0;while(els.onlineCall.disabled){assert(++turns<400);if(!els.onlineResult.hidden){els.confirmOnlineReset.onclick();continue}const [id,f]=pending.entries().next().value||[];assert(f,'AI timer missing before raise test');pending.delete(id);f()}els.onlineRaiseAmount.value=String(Number(els.onlineRaiseRange.max));els.onlineRaiseAmount.onchange({target:els.onlineRaiseAmount});const selected=els.onlineRaiseAmount.value;await ctx.RiverTransport;/* Re-render via unchanged table update. */
await Promise.resolve();assert.equal(els.onlineRaiseAmount.value,selected,'sync must preserve selected raise');els.onlineFold.onclick();
console.log('PASS: '+capacity+' seats, 8 completed hands, private cards, journal, next-hand availability, raise selection retained');
})().catch(e=>{console.error(e);process.exitCode=1});
