import { DurableObject } from 'cloudflare:workers';
import './poker.js';
import './multiplayer.js';
const M=globalThis.MultiPoker;
const cleanName=v=>String(v||'无名牌手').trim().slice(0,16)||'无名牌手';
const response=(data,status=200,origin='')=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json;charset=utf-8','Access-Control-Allow-Origin':origin,'Vary':'Origin','Cache-Control':'no-store'}});
export default {async fetch(request,env){const u=new URL(request.url),origin=request.headers.get('Origin')||'',allowed=(env.ALLOWED_ORIGINS||'').split(',');if(origin&&!allowed.includes(origin))return response({error:'不允许的来源'},403);if(request.method==='OPTIONS')return new Response(null,{headers:{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400','Vary':'Origin'}});try{if(u.pathname==='/api/health')return response({ok:true,version:'0.0.2'},200,origin);if(u.pathname==='/api/rooms'&&request.method==='POST'){if(Number(request.headers.get('Content-Length')||0)>4096)return response({error:'请求过大'},413,origin);const raw=await request.text();if(raw.length>4096)return response({error:'请求过大'},413,origin);const data=JSON.parse(raw),code=crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase(),stub=env.ROOMS.getByName(code);const r=await stub.fetch(new Request('https://room/initialize',{method:'POST',body:JSON.stringify({...data,code})}));return response(await r.json(),r.status,origin)}const match=u.pathname.match(/^\/api\/rooms\/([A-Fa-f0-9]{12})\/ws$/);if(match&&request.method==='GET'){if(request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return response({error:'需要实时连接'},426,origin);return env.ROOMS.getByName(match[1].toUpperCase()).fetch(request)}return response({error:'不存在的接口'},404,origin)}catch{return response({error:'请求无法处理'},400,origin)}}};
export class PokerRoom extends DurableObject {
 constructor(ctx,env){super(ctx,env);this.room=null;this.queue=Promise.resolve();ctx.blockConcurrencyWhile(async()=>{this.room=await ctx.storage.get('room')||null});ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping','pong'))}
 serialize(fn){const p=this.queue.then(fn);this.queue=p.catch(()=>{});return p}
 async fetch(request){return this.serialize(async()=>{const u=new URL(request.url);if(u.pathname==='/initialize'){if(this.room)return response({error:'房间已存在'},409);const d=await request.json();const capacity=[2,4,6].includes(Number(d.capacity))?Number(d.capacity):6,stack=[1000,2000,5000].includes(Number(d.stack))?Number(d.stack):2000,blind=[20,50,100].includes(Number(d.blind))?Number(d.blind):20,token=crypto.randomUUID();this.room={code:d.code,capacity,stack,blind,seats:[{id:crypto.randomUUID(),token,name:cleanName(d.name),bot:false,ready:false}],host:0,game:null,deadline:null,version:0,activity:Date.now(),created:Date.now()};await this.persist();return response({code:d.code,token},201)}if(!this.room)return response({error:'房间不存在或已结束'},404);if(this.room.activity<Date.now()-86400000)return response({error:'房间已过期'},410);if(this.ctx.getWebSockets().length>=18)return response({error:'房间连接过多'},429);const pair=new WebSocketPair(),[client,server]=Object.values(pair);this.ctx.acceptWebSocket(server);server.serializeAttachment({seat:-1,joined:false,count:0,window:Date.now()});return new Response(null,{status:101,webSocket:client})})}
 connected(i){return this.ctx.getWebSockets().some(ws=>{const a=ws.deserializeAttachment();return a?.joined&&a.seat===i})}
 async persist(){this.room.activity=Date.now();await this.ctx.storage.put('room',this.room);await this.ctx.storage.setAlarm(this.room.deadline||this.room.activity+86400000)}
 emit(ws,data){try{ws.send(JSON.stringify(data))}catch{}}
 publicState(i){const r=this.room;return {type:'state',code:r.code,seat:i,host:r.host,capacity:r.capacity,stack:r.stack,blind:r.blind,version:r.version,deadline:r.deadline,serverTime:Date.now(),seats:r.seats.map((s,j)=>({name:s.name,bot:s.bot,ready:s.ready,connected:s.bot||this.connected(j)})),game:r.game?M.view(r.game,i):null}}
 broadcast(){for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment();if(a?.joined)this.emit(ws,this.publicState(a.seat))}}
 async webSocketMessage(ws,message){return this.serialize(async()=>{try{if(typeof message!=='string'||message.length>2048)throw Error('消息不合法');const a=ws.deserializeAttachment();if(!a)return;const now=Date.now();if(now-a.window>10000){a.window=now;a.count=0}if(++a.count>35){ws.close(1008,'操作过于频繁');return}ws.serializeAttachment(a);if(!a.joined&&now-a.window>20000){ws.close(1008,'连接超时');return}const d=JSON.parse(message),r=this.room;if(!r)throw Error('房间已结束');if(d.type==='join'){let i=r.seats.findIndex(s=>!s.bot&&s.token===d.token);if(i<0){if(r.game&&!r.game.done)throw Error('本手进行中，请下一手再加入');if(r.seats.length>=r.capacity)throw Error('房间已满');i=r.seats.length;r.seats.push({id:crypto.randomUUID(),token:crypto.randomUUID(),name:cleanName(d.name),bot:false,ready:false})}for(const other of this.ctx.getWebSockets()){const old=other.deserializeAttachment();if(other!==ws&&old?.joined&&old.seat===i){old.joined=false;other.serializeAttachment(old);other.close(1000,'已在另一窗口接入')}}a.seat=i;a.joined=true;ws.serializeAttachment(a);this.emit(ws,{type:'joined',token:r.seats[i].token,seat:i});r.version++;await this.persist();this.broadcast();return}if(!a.joined)throw Error('请先加入房间');const i=a.seat;if(d.type==='sync'){this.emit(ws,this.publicState(i));return}if(d.version!==r.version)throw Error('牌桌已更新，请按最新状态操作');if(d.type==='ready'){if(r.game&&!r.game.done)throw Error('当前牌局未结束');r.seats[i].ready=!r.seats[i].ready}else if(d.type==='addBot'){if(i!==r.host)throw Error('仅房主可以添加 AI');if(r.game&&!r.game.done)throw Error('请在牌局结束后添加');if(r.seats.length>=r.capacity)throw Error('房间已满');r.seats.push({id:crypto.randomUUID(),name:'AI '+(r.seats.filter(s=>s.bot).length+1),bot:true,ready:true})}else if(d.type==='start'){if(i!==r.host)throw Error('仅房主可以发牌');if(r.seats.length<2)throw Error('至少需要两位牌手');if(r.game&&!r.game.done)throw Error('当前牌局未结束');if(r.seats.some((s,j)=>!s.bot&&(!s.ready||!this.connected(j))))throw Error('请等待所有朋友上线并准备');if(!r.game){r.game=M.create(r.seats.map(()=>r.stack),r.seats.map(s=>s.name),r.blind)}else{for(let j=r.game.players.length;j<r.seats.length;j++)r.game.players.push(M.create([r.stack],[r.seats[j].name]).players[0]);if(r.game.players.filter(p=>p.stack>0).length<2)throw Error('本桌已分出胜负，房主可以重新开桌')}M.begin(r.game);this.setDeadline()}else if(d.type==='act'){if(!r.game||r.game.done)throw Error('当前没有进行中的牌局');M.act(r.game,i,d.kind,d.to);this.setDeadline();if(r.game.done)for(const s of r.seats)if(!s.bot)s.ready=false}else if(d.type==='reset'){if(i!==r.host||r.game&&!r.game.done)throw Error('仅房主可在本手结束后重新开桌');r.game=null;r.deadline=null;for(const s of r.seats)if(!s.bot)s.ready=false}else throw Error('不支持的操作');r.version++;await this.persist();this.broadcast()}catch(e){this.emit(ws,{type:'error',message:e.message});if(this.room)this.emit(ws,this.publicState(ws.deserializeAttachment()?.seat??-1))}})}
 setDeadline(){const r=this.room;r.deadline=r.game&&!r.game.done?Date.now()+(r.seats[r.game.turn]?.bot?750:30000):null}
 async alarm(){return this.serialize(async()=>{const r=this.room;if(!r)return;if(r.deadline&&r.deadline<=Date.now()){const i=r.game.turn;if(r.seats[i].bot){const d=M.ai(r.game,i);M.act(r.game,i,d.kind,d.to)}else{const l=M.legal(r.game,i);M.act(r.game,i,l.check?'check':'fold')}this.setDeadline();if(r.game.done)for(const s of r.seats)if(!s.bot)s.ready=false;r.version++;await this.persist();this.broadcast()}else if(!r.deadline){if(r.activity+86400000<=Date.now()){for(const ws of this.ctx.getWebSockets())ws.close(1000,'房间已过期');await this.ctx.storage.deleteAll();this.room=null}else await this.ctx.storage.setAlarm(r.activity+86400000)}else await this.ctx.storage.setAlarm(r.deadline)})}
 async webSocketClose(ws,code,reason){return this.serialize(async()=>{try{ws.close(code,reason)}catch{}this.broadcast()})}
 async webSocketError(ws){try{ws.close(1011,'连接错误')}catch{}this.broadcast()}
}
